-- =====================================================================
-- Seed: Superadmin is auto-created by the backend on first startup
-- (see backend/src/utils/bootstrap.js).
--
-- Default credentials:
--   username: superadmin
--   password: set SUPERADMIN_PASSWORD in backend/.env before first start
--
-- This file exists only to document the seed and is intentionally a no-op.
-- =====================================================================
SELECT 1;
